### ISSUE TITLE
Link to app store download broken

### ISSUE THREAD

**Issue by thundergolfer** [architjn/Auro#13]
I have opted-in for beta testing, and then followed the link to download the app.

The link is [https://play.google.com/store/apps/detailsid=com.architjn.acjmusicplayer](https://play.google.com/store/apps/details?id=com.architjn.acjmusicplayer)

Following that link leads to a screen that says that 

> We're sorry, the requested URL was not found on this server.

**Comment by architjn** [comment]
it takes some time to get in beta
please check again in some time
