### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by AkshayChordiya** [architjn/Auro#2]
Hi,

Your page seems exciting but it would be great if there were couple of screenshots as it's not easy to clone source, build apk & then see.

I hope you add some screenshots. Thanks

**Comment by architjn** [comment]
I will add it
Untill then check here
https://plus.google.com/communities/114246584066469121582

**Comment by architjn** [comment]
I will add it
Untill then check here
https://plus.google.com/communities/114246584066469121582

**Comment by AkshayChordiya** [comment]
@architjn 
Okay, thanks.
