### ISSUE TITLE
Not issue but want to ask a question

### ISSUE THREAD

**Issue by arsalanengr** [architjn/Auro#22]
Hey i want to built a music player using your code so i have to make app exactly like that? or can i change the ui little bit? and secondly it is must to make my code open source?

**Comment by architjn** [comment]
No need to make open source
You can change UI totally as you like

**Comment by arsalanengr** [comment]
thanks for quick response and thank you so much! i will send you the link when i'll publish the app :)

**Comment by architjn** [comment]
☺
