### ISSUE TITLE
Licensing conflicts

### ISSUE THREAD

**Issue by Calinou** [architjn/Auro#6]
This project uses GPLv2, yet many of your own "clauses" are going against the very nature of it:

> ## If you are creating your own music player
> - Proper credits should be given to Auro's owner
> - Music player should not sell any ads or should not be paid
> - Icon of your application should not be similar to Auro's Icon
> - Name should not be similar to Auro
> 
> **(If any of the points above is not followed, we can take any legal action)**

Especially this one:

> Music player should not sell any ads or should not be paid

**Comment by taimur97** [comment]
+1

**Comment by architjn** [comment]
I am sorry i had no idea while starting the project about licenses
i have updated them and rules are also changed

**Comment by Calinou** [comment]
Creative Commons licenses are not made to be applied on software, with the exception of CC0.

**Comment by architjn** [comment]
Then please you tell me what suits best for this software?

**Comment by Calinou** [comment]
Try this site: [Choose a license](http://choosealicense.com/).

**Comment by maateo** [comment]
Have you looked at Apache License 2.0? 

If you navigate to trademarks (point number 6) on http://www.apache.org/licenses/LICENSE-2.0, you'll see that "This License does not grant permission to use the trade names, trademarks, service marks, or product names of the Licensor, except as required for reasonable and customary use in describing the origin of the Work and reproducing the content of the NOTICE file."

Also, here's a quick summary of the license https://www.tldrlegal.com/l/apache2, if you're interested in it.
